# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_SUPPORT_CRASH_REASON) += crashLog/
obj-$(CONFIG_HMD_SWAPPINESS_OPT) += swappiness/
obj-$(CONFIG_HMD_BOOTMSG) += bootmsg/
obj-$(CONFIG_DEBUG_BOOTLOADER_LOG) += bootloader_log/
